#+title: Como Praticar Habilidades
Uma das coisas mais fáceis de serem ignoradas em estudantes é, incrivelmente, a que mais dá para eles a capacidade de entender: a prática! É quase impossível aprender uma habilidade sem você investir um tempo em praticar o que você sabe sobre ela para que te permita enfrentar problemas, visualizar a execução e entender novos pontos que precisam ser pesquisados e melhorados.

Você não vai evoluir como programador somente lendo livros e consumindo cursos como louco, deixando de investir um tempo maior ou proporcional de praticar o que aprendeu e desenvolver projetos, para poder enfrentar problemas e quebrar a cabeça sobre suas habilidades; isso é uma das principais formas de evolução. E isso também vale para outras áreas, como Segurança Ofensiva, onde você precisa ainda mais visualizar a execução de habilidades e conceitos para conseguir entendê-los completamente. Hoje o que vou trazer são sugestões para você praticar seus conhecimentos coerentemente, e claro, uma observação importante é que vou dar foco exclusivamente para programação, considerando ser a habilidade que mais abrange áreas que serão abordadas.
  
** Projetos Pessoais
Algo que fiz e me trouxe uma experiência enorme na minha vida, e uma referência do quanto consegui evoluir, são projetos pessoais que me seguiram durante todas as fases da minha vida. Claro, nem todo mundo vai começar um projeto que vai durar a vida toda, mas você pode criar projetos que vão te seguir durante seu tempo de estudo e aprofundamento.

Se hoje você for começar a estudar a linguagem C, você em algum momento vai parar de fazer pequenos programas de calculadoras e listas e começar a sentir que precisa desenvolver um projeto mais relevante para sentir que está evoluindo, e é onde vai entrar esse tópico: desenvolver um projeto que vai te acompanhar durante essa fase para que você possa visualizar suas evoluções por você mesmo. Continuando no exemplo do C, você poderia desenvolver uma biblioteca de manipulação de arquivos, por exemplo, que você vai tornando cada vez mais dinâmica e útil conforme você aprende mais, saindo de uma biblioteca muito estática para uma muito bem flexível para todas as situações da sua vida. Isso, na minha visão, é uma das coisas que mais te ajudam a fugir do sentimento de /impostor/ que pode aparecer e te desanimar de você mesmo.

Mas não se limite a um só projeto, ou um só tipo, é somente um exemplo! Troque biblioteca por gerenciador de agenda para te ajudar a estudar, um despertador, um programa que conserte algum trabalho chato e repetitivo da sua vida, entre outros. Muitos programadores não dependem em si de terem mentes geniais para desenvolverem projetos, a grande maioria deles nasce da *necessidade* de possuir aquilo. O próprio *GIT* nasceu para resolver um problema do Linus Torvalds no desenvolvimento do Linux, e estamos falando do gerenciador de versionamento mais importante atualmente do mundo; uma necessidade dele foi a resolução das necessidades de milhares de programadores no mundo. Está acordando atrasado? Não baixe um despertador, faça um você mesmo! Sentir necessidade e desenvolver é uma ótima forma de praticar!  

Então, como resolução deste tópico, eu quero resumir rapidamente que você deve ter projetos pessoais seus que envolvam necessidades suas no dia a dia, que podem ser úteis para você mesmo e com suas habilidades. Não tente criar o novo Linux ou Git, tente criar aquilo que você vai precisar e NUNCA desista! Programação é uma forma bem parecida com o que a ciência moderna faz: é encontrar uma solução e resposta para necessidades ou perguntas que temos, e não ser um gênio desenvolvedor de projetos. 
